version: '3'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    hostname: mariadb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=savingssites_db
      - MARIADB_PASSWORD=vmYlZdpsTcXm
      - MARIADB_DATABASE=savingssites
      - MARIADB_ROOT_PASSWORD=root
  #    ports:
  #      - '3306:3306'
    volumes:
      #- ./savingssites.sql:/docker-entrypoint-initdb.d/savingssites.sql
        #- ./import-sql.sh:/docker-entrypoint-initdb.d/import-sql.sh
         - mysql:/var/lib/mysql/
  redis:
    hostname: redis 
    image: bitnami/redis:latest
    ports:
      - '6380:6380'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis:/bitnami
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './html:/var/www/html'
      - './config/subdomain.conf:/etc/apache2/sites-enabled/subdomain.conf'
      - './config/STAR.savingssites.com.crt:/etc/ssl/STAR.savingssites.com.crt'
      - './config/STAR.savingssites.com_key.pem:/etc/ssl/STAR.savingssites.com_key.pem'
    depends_on:
      - mariadb
      - redis
volumes:
    mysql:
    redis:
